### ISSUE TITLE
Just a note about GLBuffers

### ISSUE THREAD

**Issue by Mehran7kl** [DonDejvo/3d-game#1]
https://github.com/DonDejvo/3d-game/blob/643e4ca6b018f78c802b580c7269037ae5307729/src/main.js#L1036
As far as I know glBufferSubData is the only right way to update a buffer , glBufferData theoricaly will result a buffer storage recreation.
Great work at all.

**Comment by DonDejvo** [comment]
You are right, anyway if you check usage of `submitBuffer` method, I use it only once in beginning.
Since then there is no updating, the purpose of the buffer is to keep level and models geometry (I save start index and size of each model) and then I use uniforms to position, rotate and scale when drawing them.
Thank you for liking my unfinished project.
